# Done to increase performance on CI, also avoids issue with Daemon
org.gradle.daemon=false

# Minecraft Properties
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10:v2
loader_version=0.15.11

# Mod Properties
mod_version=1.0.0
maven_group=cz.czsksmp.dialogblocker
archives_base_name=dialogblocker

# Dependencies
fabric_version=0.92.2+1.20.1
